/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MainView;

import java.awt.Color;
import java.util.Map;

/**
 *
 * @author HP
 */
public class MenuNew extends javax.swing.JPanel {

    /**
     * Creates new form MenuNew
     */
    
    public Map<String, Object> currentUser;
    public MenuNew() {
        initComponents();
//        this.currentUser = user;
//        labelNama.setText((String) user.get("fullName"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtDate = new javax.swing.JLabel();
        lbl_nama = new javax.swing.JLabel();
        pn_container = new javax.swing.JPanel();
        pn_menuMain = new javax.swing.JPanel();
        btn_register = new javax.swing.JPanel();
        lb_register = new javax.swing.JLabel();
        btn_register1 = new javax.swing.JPanel();
        lb_register1 = new javax.swing.JLabel();
        btn_register2 = new javax.swing.JPanel();
        lb_register2 = new javax.swing.JLabel();

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDate.setForeground(new java.awt.Color(255, 255, 255));
        txtDate.setText("Date");

        lbl_nama.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_nama.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nama.setText("NamaDokter");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(txtDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 904, Short.MAX_VALUE)
                .addComponent(lbl_nama)
                .addContainerGap(278, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nama)
                    .addComponent(txtDate))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pn_container.setBackground(new java.awt.Color(255, 255, 255));
        pn_container.setPreferredSize(new java.awt.Dimension(1400, 567));

        pn_menuMain.setBackground(new java.awt.Color(255, 255, 255));

        btn_register.setBackground(new java.awt.Color(102, 255, 102));
        btn_register.setBorder(new javax.swing.border.MatteBorder(null));
        btn_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registerMouseExited(evt);
            }
        });

        lb_register.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_register.setForeground(new java.awt.Color(255, 255, 255));
        lb_register.setText("REGISTER");

        javax.swing.GroupLayout btn_registerLayout = new javax.swing.GroupLayout(btn_register);
        btn_register.setLayout(btn_registerLayout);
        btn_registerLayout.setHorizontalGroup(
            btn_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_registerLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lb_register)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        btn_registerLayout.setVerticalGroup(
            btn_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_registerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_register)
                .addGap(62, 62, 62))
        );

        btn_register1.setBackground(new java.awt.Color(102, 102, 255));
        btn_register1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_register1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_register1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_register1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_register1MouseExited(evt);
            }
        });

        lb_register1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_register1.setForeground(new java.awt.Color(255, 255, 255));
        lb_register1.setText("ASSESMENT");

        javax.swing.GroupLayout btn_register1Layout = new javax.swing.GroupLayout(btn_register1);
        btn_register1.setLayout(btn_register1Layout);
        btn_register1Layout.setHorizontalGroup(
            btn_register1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_register1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(lb_register1)
                .addGap(39, 39, 39))
        );
        btn_register1Layout.setVerticalGroup(
            btn_register1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_register1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lb_register1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addGap(56, 56, 56))
        );

        btn_register2.setBackground(new java.awt.Color(255, 0, 51));
        btn_register2.setBorder(new javax.swing.border.MatteBorder(null));
        btn_register2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_register2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_register2MouseEntered(evt);
            }
        });

        lb_register2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_register2.setForeground(new java.awt.Color(255, 255, 255));
        lb_register2.setText("LOGOUT");

        javax.swing.GroupLayout btn_register2Layout = new javax.swing.GroupLayout(btn_register2);
        btn_register2.setLayout(btn_register2Layout);
        btn_register2Layout.setHorizontalGroup(
            btn_register2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_register2Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(lb_register2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        btn_register2Layout.setVerticalGroup(
            btn_register2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_register2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lb_register2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout pn_menuMainLayout = new javax.swing.GroupLayout(pn_menuMain);
        pn_menuMain.setLayout(pn_menuMainLayout);
        pn_menuMainLayout.setHorizontalGroup(
            pn_menuMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_menuMainLayout.createSequentialGroup()
                .addGap(419, 419, 419)
                .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(btn_register1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(90, 90, 90)
                .addComponent(btn_register2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(363, 363, 363))
        );
        pn_menuMainLayout.setVerticalGroup(
            pn_menuMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_menuMainLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(pn_menuMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_register1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_register2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(238, 238, 238))
        );

        javax.swing.GroupLayout pn_containerLayout = new javax.swing.GroupLayout(pn_container);
        pn_container.setLayout(pn_containerLayout);
        pn_containerLayout.setHorizontalGroup(
            pn_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_containerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pn_menuMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pn_containerLayout.setVerticalGroup(
            pn_containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_menuMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(pn_container, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registerMouseClicked

        jPanel1.removeAll();
        jPanel1.add(new RegisterPasienNew());
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_btn_registerMouseClicked

    private void btn_register1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_register1MouseClicked
        jPanel1.removeAll();
        jPanel1.add(new Assesment());
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_btn_register1MouseClicked

    private void btn_register2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_register2MouseClicked
        //      currentUser = null;
        jPanel1.removeAll();
        jPanel1.add(new Login());
        jPanel1.repaint();
        jPanel1.revalidate();

        // Menutup aplikasi dan kembali ke form login
    }//GEN-LAST:event_btn_register2MouseClicked

    private void btn_registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registerMouseEntered
        btn_register.setBackground(new Color(102,105,102));
    }//GEN-LAST:event_btn_registerMouseEntered

    private void btn_registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registerMouseExited
        btn_register.setBackground(new Color(102,255,102));
    }//GEN-LAST:event_btn_registerMouseExited

    private void btn_register1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_register1MouseEntered
        btn_register1.setBackground(new Color(102,105,102));
    }//GEN-LAST:event_btn_register1MouseEntered

    private void btn_register1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_register1MouseExited
        btn_register1.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_btn_register1MouseExited

    private void btn_register2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_register2MouseEntered
        btn_register2.setBackground(new Color(102,105,102));
    }//GEN-LAST:event_btn_register2MouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_register;
    private javax.swing.JPanel btn_register1;
    private javax.swing.JPanel btn_register2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_register;
    private javax.swing.JLabel lb_register1;
    private javax.swing.JLabel lb_register2;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JPanel pn_container;
    private javax.swing.JPanel pn_menuMain;
    private javax.swing.JLabel txtDate;
    // End of variables declaration//GEN-END:variables
}
